In [2]:
import numpy as np
from scipy.linalg import null_space

In [4]:
m = np.random.randn(2,4)

null_space(m)

array([[-0.71073195, -0.21693369],
       [-0.05265619, -0.8565744 ],
       [ 0.61845066, -0.07481263],
       [-0.33106828,  0.46219384]])

# Exercises

In [8]:
m1 = np.random.randn(4,3)@np.random.randn(3,4)
m2 = np.random.randn(4,3)@np.random.randn(3,4)

n = null_space(m1)

print(m2@m1@n) #supposed to be zero matrix but differs due to machine differences
print(m1@m2@n)

[[-1.11022302e-16]
 [ 1.11022302e-16]
 [ 1.11022302e-16]
 [ 2.77555756e-16]]
[[-1.88881887]
 [ 0.05217549]
 [-0.48541007]
 [-0.17092015]]


In [17]:
m1 = np.random.randn(16,9)@np.random.randn(9,11)

rn = null_space(m1)
ln = null_space(m1.T)

# since the rank of the matrix equals the dimensions of row spaces equals dimensions of column space
r = np.linalg.matrix_rank(m1)

print(rn.shape[1] + r)
print(ln.shape[1] + r)

11
16
