In [1]:
import numpy as np

# Transposing Matrices

In [2]:
matrix = np.random.randn(3,6)
print(matrix.shape)

#Transpose matrix - rows become columns, columns become rows
print(matrix.T.shape)

(3, 6)
(6, 3)


# Identity, Ones, and Zeros Matrices

In [4]:
print(np.eye(4))
print(np.ones(4))
print(np.zeros((4,4)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 1. 1. 1.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Diagonal Matrix

In [7]:
print(np.diag([2,4,6,8]))

R = np.random.randn(3,4)

print(R)

#find diagonal elements of matrix
print(np.diag(R))



[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
[[ 0.72877781 -0.80770337  0.47585919 -1.35110008]
 [-0.30684165 -1.33412106  0.00352233  0.56233964]
 [-0.82125132  1.93242131 -0.08018456  0.0305084 ]]
[ 0.72877781 -1.33412106 -0.08018456]


# Augmenting (concatenating matrices)

In [9]:
A = np.random.randn(3,5)
B = np.random.randn(3,6)

AB = np.concatenate([A,B], axis = 1)
AB.shape

(3, 11)

# Triangular Matrix

In [2]:
matrix = np.random.randn(5,5)

#Lower triangle
print(np.tril(matrix))

#Upper triangle
print(np.triu(matrix))

[[-0.07075823  0.          0.          0.          0.        ]
 [-2.92851308 -1.21632103  0.          0.          0.        ]
 [-0.18482492 -0.89051937  0.97265124  0.          0.        ]
 [ 0.40518686 -0.31847378 -0.06777768  0.54321401  0.        ]
 [ 0.22592029  1.51254756  1.23674033 -0.27248622  0.03532642]]
[[-0.07075823 -0.13424075  0.53588364  0.27887118 -0.13426354]
 [ 0.         -1.21632103 -0.72094901 -0.2890403   0.02684302]
 [ 0.          0.          0.97265124 -0.29444747 -1.54595336]
 [ 0.          0.          0.          0.54321401 -0.37109224]
 [ 0.          0.          0.          0.          0.03532642]]


# Hankel and Toeplitz Matrices

In [3]:
from scipy.linalg import hankel, toeplitz

t = [1,2,3,4]

print(hankel(t))
print(toeplitz(t))

[[1 2 3 4]
 [2 3 4 0]
 [3 4 0 0]
 [4 0 0 0]]
[[1 2 3 4]
 [2 1 2 3]
 [3 2 1 2]
 [4 3 2 1]]


# Shifting a matrix

In [5]:
y = 0.2
identity = np.eye(4)
matrix = np.random.randn(4)

print(matrix)
print(matrix + y*identity)

[-1.96270036  0.3729371  -0.16723422 -0.69037699]
[[-1.76270036  0.3729371  -0.16723422 -0.69037699]
 [-1.96270036  0.5729371  -0.16723422 -0.69037699]
 [-1.96270036  0.3729371   0.03276578 -0.69037699]
 [-1.96270036  0.3729371  -0.16723422 -0.49037699]]


# Calculating Trace - Sum of Diagonal

In [13]:
matrix = np.random.rand(4,4)
print(np.trace(matrix))

2.014305944575812


# Code Challenges

In [18]:
m1 = np.random.randn(4,2)
m2 = np.random.randn(4,2)

for coli in range(2):
    for colj in range(2):
        print(np.dot(m1[:, coli], m2[:, colj]))

3.2736003511136706
2.1616240892759606
0.3351857207788501
0.10346474601471381


In [19]:
m = np.random.randn(5,5)

mT = np.tril(m)

print(mT + mT.T)

[[ 0.1187131  -0.71930021  0.84788428 -0.69922095 -0.74886515]
 [-0.71930021 -0.48062646 -0.72277009 -0.29471687  0.65271184]
 [ 0.84788428 -0.72277009 -2.44294801 -0.39702975 -0.08035949]
 [-0.69922095 -0.29471687 -0.39702975  0.94144045 -0.73353754]
 [-0.74886515  0.65271184 -0.08035949 -0.73353754  1.73614321]]


In [22]:
m = np.zeros((4,8))

for i in range(4):
    m[i,i] = i + 1

print(m)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0.]]
