In [2]:
import numpy as np
from numpy.random import randn

# Matrix multiplication

In [4]:
m1 = randn(4,3)
m2 = randn(3,5)

print(m1 @ m2)

[[ 1.53654297  1.89614265  1.67787192  2.65792929 -0.2179245 ]
 [-1.00914664 -1.62483757 -1.30939585 -0.61721965  0.75845391]
 [ 0.25177599 -0.41121937 -0.08141871  0.88161097  0.46667337]
 [-0.66122459 -2.46595009 -1.52899982 -0.45806866  1.11083434]]
