In [2]:
import numpy as np
import sympy as sym

# MCA Algorithm

In [4]:
m = np.random.randn(3,3)

mi = np.linalg.inv(m)

m@mi

array([[ 1.00000000e+00, -7.08514640e-15, -2.36422783e-16],
       [ 1.32271145e-15,  1.00000000e+00, -5.49704200e-17],
       [ 1.22883716e-15, -1.04554120e-14,  1.00000000e+00]])

# Inverse via row reduction

In [2]:
m = np.random.rand(3,3)

mConcat = np.concatenate((m, np.eye(3,3)), axis = 1)

mRR = sym.Matrix(mConcat).rref()[0]

# keeps what was formally the identify maxrix, now transfored by row reduction
mRR = mRR[:, 3:]

# Left/Right Inverse

In [5]:
#left inverse
m = np.random.randn(5,3)
inverseL = np.linalg.inv(m.T@m)@m.T
print(inverseL@m)

#right inverse
n = np.random.randn(3,5)
inverseR = n.T@np.linalg.inv(n@n.T)
print(n@inverseR)

[[ 1.00000000e+00  3.72479759e-16  1.22227043e-16]
 [-4.49327669e-16  1.00000000e+00  2.96254039e-16]
 [ 4.21565535e-16 -6.13979148e-17  1.00000000e+00]]
[[ 1.00000000e+00  9.02827280e-17 -6.92923818e-17]
 [-3.61931571e-17  1.00000000e+00 -1.75246381e-17]
 [ 3.90367929e-17 -1.32107250e-17  1.00000000e+00]]


# MP Pseudoinverse

In [8]:
m = np.random.randn(3,3)

m[1, :] = m[0, :]

print(np.linalg.pinv(m)@m)

[[ 0.96890449  0.06239159 -0.1619749 ]
 [ 0.06239159  0.87481439  0.32499455]
 [-0.1619749   0.32499455  0.15628112]]
