In [1]:
import numpy as np
from numpy.random import randn

# Matrix multiplication

In [4]:
m1 = randn(4,3)
m2 = randn(3,5)

print(m1 @ m2)

[[ 1.53654297  1.89614265  1.67787192  2.65792929 -0.2179245 ]
 [-1.00914664 -1.62483757 -1.30939585 -0.61721965  0.75845391]
 [ 0.25177599 -0.41121937 -0.08141871  0.88161097  0.46667337]
 [-0.66122459 -2.46595009 -1.52899982 -0.45806866  1.11083434]]


# Hadamard (element-wise) Multiplication

In [2]:
m1 = randn(4,4)
m2 = randn(4,4)

print(m1 * m2)

[[ 0.66296233 -5.98258006 -1.23964023 -0.27729164]
 [-0.11220731 -0.03355995  1.48524247 -0.72820206]
 [-0.41153553  0.55635629 -0.62267846  0.07550936]
 [ 0.41098535 -0.2709707   0.11418412 -1.86365811]]


# Vectorizing a Matrix

In [3]:
M = np.array([ [1,2,3], [4,5,6] ])
print(M.flatten(order = 'F'))

[1 4 2 5 3 6]


# Frobenius Dot Product

In [4]:
m1 = randn(4,4)
m2 = randn(4,4)

print(np.trace(m1.T@m2))

0.054974154924251284
