In [1]:
import numpy as np

# Computing Dot Product

In [4]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

#Takes two vectors of equal dimensions and returns a scalar - aka Scalar Multiplication
print(np.dot(v1, v2))

32


# Linear Weighted Combination

In [3]:
w1 = 2
w2 = -3
w3 = 4

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
v3 = np.array([7,8,9])

print(w1*v1 + w2*v2 + w3*v3)

[18 21 24]


# Outer Product

In [3]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print(np.outer(v1,v2))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


# Element-wise (Hadamard) vector product

In [4]:
# a useful way to organize a set of scalar multiplications
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print(v1*v2)

[ 4 10 18]


# Unit Vector

In [2]:
v = np.array([1,2,3])

vNorm = np.linalg.norm(v)

#division is the same as multiplying by reciprocal
print(v/vNorm)

[0.26726124 0.53452248 0.80178373]


# Code Challanges

## 3.12.1

In [4]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])
v3 = np.array([2,4,6,8,10])

w = [3,6,9]

print(v1*w[0] + v2*w[1] + v3*w[2])

[ 57  84 111 138 165]


## 3.12.2

In [5]:
v1 = np.array([3,4,5])
v2 = np.array([1,1,1])

print(f'Mean of v1: {np.dot(v1,v2)/len(v1)}')

Mean of v1: 4.0


## 3.12.3

In [6]:
v1 = np.array([3,4,5])
v2 = np.array([1,1.5,2])

print(f'Mean of v1: {np.dot(v1,v2)/len(v1)}')

Mean of v1: 6.333333333333333


In [8]:
v1 = np.array([3,4,5])
v2 = np.array([1,1.5,2])

print(f'Mean of v1: {np.dot(v1,v2/sum(v2))}')

Mean of v1: 4.222222222222222
