In [1]:
import numpy as np

# Transposing Matrices

In [2]:
matrix = np.random.randn(3,6)
print(matrix.shape)

#Transpose matrix - rows become columns, columns become rows
print(matrix.T.shape)

(3, 6)
(6, 3)


# Identity, Ones, and Zeros Matrices

In [4]:
print(np.eye(4))
print(np.ones(4))
print(np.zeros((4,4)))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 1. 1. 1.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Diagonal Matrix

In [7]:
print(np.diag([2,4,6,8]))

R = np.random.randn(3,4)

print(R)

#find diagonal elements of matrix
print(np.diag(R))



[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
[[ 0.72877781 -0.80770337  0.47585919 -1.35110008]
 [-0.30684165 -1.33412106  0.00352233  0.56233964]
 [-0.82125132  1.93242131 -0.08018456  0.0305084 ]]
[ 0.72877781 -1.33412106 -0.08018456]


# Augmenting (concatenating matrices)

In [9]:
A = np.random.randn(3,5)
B = np.random.randn(3,6)

AB = np.concatenate([A,B], axis = 1)
AB.shape

(3, 11)