In [2]:
import numpy as np
import sympy as sym

# MCA Algorithm

In [4]:
m = np.random.randn(3,3)

mi = np.linalg.inv(m)

m@mi

array([[ 1.00000000e+00, -7.08514640e-15, -2.36422783e-16],
       [ 1.32271145e-15,  1.00000000e+00, -5.49704200e-17],
       [ 1.22883716e-15, -1.04554120e-14,  1.00000000e+00]])

# Inverse via row reduction

In [2]:
m = np.random.rand(3,3)

mConcat = np.concatenate((m, np.eye(3,3)), axis = 1)

mRR = sym.Matrix(mConcat).rref()[0]

# keeps what was formally the identify maxrix, now transfored by row reduction
mRR = mRR[:, 3:]

# Left/Right Inverse

In [5]:
#left inverse
m = np.random.randn(5,3)
inverseL = np.linalg.inv(m.T@m)@m.T
print(inverseL@m)

#right inverse
n = np.random.randn(3,5)
inverseR = n.T@np.linalg.inv(n@n.T)
print(n@inverseR)

[[ 1.00000000e+00  3.72479759e-16  1.22227043e-16]
 [-4.49327669e-16  1.00000000e+00  2.96254039e-16]
 [ 4.21565535e-16 -6.13979148e-17  1.00000000e+00]]
[[ 1.00000000e+00  9.02827280e-17 -6.92923818e-17]
 [-3.61931571e-17  1.00000000e+00 -1.75246381e-17]
 [ 3.90367929e-17 -1.32107250e-17  1.00000000e+00]]


# MP Pseudoinverse

In [8]:
m = np.random.randn(3,3)

m[1, :] = m[0, :]

print(np.linalg.pinv(m)@m)

[[ 0.96890449  0.06239159 -0.1619749 ]
 [ 0.06239159  0.87481439  0.32499455]
 [-0.1619749   0.32499455  0.15628112]]


# Code Challange

In [11]:
size = 4
A = np.random.randn(size, size)
M = np.zeros((size, size))
G = np.zeros((size, size))

for i in range(size):
    for j in range(size):
        rows = [True]*size
        rows[i] = False

        columns = [True]*size
        columns[j] = False

        M[i, j] = np.linalg.det(A[rows, :][:, columns])

        G[i, j] = (-1)**(i+j)

C = G * M

print(C.T / np.linalg.det(A))
print(np.linalg.inv(A))


[[ 2.80903871e+00 -6.31176774e-01  4.95282819e+00 -2.13357977e+00]
 [ 7.74250351e+00 -3.75256141e+00  1.55094225e+01 -6.74538132e+00]
 [-2.54884075e+00  9.19119186e-01 -5.63308010e+00  2.87551209e+00]
 [-7.42877674e-01 -1.13171560e-02 -1.81073520e+00  6.59276036e-02]]
[[ 2.80903871e+00 -6.31176774e-01  4.95282819e+00 -2.13357977e+00]
 [ 7.74250351e+00 -3.75256141e+00  1.55094225e+01 -6.74538132e+00]
 [-2.54884075e+00  9.19119186e-01 -5.63308010e+00  2.87551209e+00]
 [-7.42877674e-01 -1.13171560e-02 -1.81073520e+00  6.59276036e-02]]


In [13]:
square = np.random.randn(3,3)

print(f'PsuedoInverse {np.linalg.pinv(square)}')
print(f'Regular Inverse {np.linalg.inv(square)}')

tall = np.random.randn(4,2)
print(f'PsuedoInverse {np.linalg.pinv(tall)}')
print(f'Regular Inverse {np.linalg.inv(tall.T@tall)@tall.T}')

PsuedoInverse [[-1.20793313  0.58928281 -0.84228499]
 [ 1.07744508  0.23999826 -0.4786209 ]
 [-1.18267631  1.70371492 -1.2895753 ]]
Regular Inverse [[-1.20793313  0.58928281 -0.84228499]
 [ 1.07744508  0.23999826 -0.4786209 ]
 [-1.18267631  1.70371492 -1.2895753 ]]
PsuedoInverse [[ 0.26020733  0.17454477  0.23056022 -0.00874159]
 [-0.11763442  0.57999109 -0.124658    0.50800481]]
Regular Inverse [[ 0.26020733  0.17454477  0.23056022 -0.00874159]
 [-0.11763442  0.57999109 -0.124658    0.50800481]]
