In [2]:
import numpy as np
from numpy.random import randn

# Matrix multiplication

In [4]:
m1 = randn(4,3)
m2 = randn(3,5)

print(m1 @ m2)

[[ 1.53654297  1.89614265  1.67787192  2.65792929 -0.2179245 ]
 [-1.00914664 -1.62483757 -1.30939585 -0.61721965  0.75845391]
 [ 0.25177599 -0.41121937 -0.08141871  0.88161097  0.46667337]
 [-0.66122459 -2.46595009 -1.52899982 -0.45806866  1.11083434]]


# Hadamard (element-wise) Multiplication

In [2]:
m1 = randn(4,4)
m2 = randn(4,4)

print(m1 * m2)

[[ 0.66296233 -5.98258006 -1.23964023 -0.27729164]
 [-0.11220731 -0.03355995  1.48524247 -0.72820206]
 [-0.41153553  0.55635629 -0.62267846  0.07550936]
 [ 0.41098535 -0.2709707   0.11418412 -1.86365811]]


# Vectorizing a Matrix

In [3]:
M = np.array([ [1,2,3], [4,5,6] ])
print(M.flatten(order = 'F'))

[1 4 2 5 3 6]


# Frobenius Dot Product

In [4]:
m1 = randn(4,4)
m2 = randn(4,4)

print(np.trace(m1.T@m2))

0.054974154924251284


# Frobenius Norm

In [2]:
m = randn(4,4)

np.linalg.norm(m, 'fro')

4.440932464248153

# Code Challenges

In [22]:
m1 = randn(2,4)
m2 = randn(4,3)

print(m1 @ m2)

m3 = np.zeros((2,3))

for i in range(m2.shape[0]):
    m3 += np.outer(m1[:, i], m2[i, :])

m3

[[-0.39841278 -8.30124865  2.09998134]
 [ 0.83656061  5.5241507   0.18875864]]


array([[-0.39841278, -8.30124865,  2.09998134],
       [ 0.83656061,  5.5241507 ,  0.18875864]])

In [24]:
m1 = np.diag([2,4,6,8])
m2 = randn(4,4)

#Hadamard Multiplication
print(m1 * m2)

#Standard
print(m1 @ m2)

#The diagonals are the same


[[ 0.34430276 -0.         -0.         -0.        ]
 [ 0.          1.10382732  0.          0.        ]
 [-0.         -0.          6.49750501 -0.        ]
 [ 0.          0.         -0.         10.33129328]]
[[  0.34430276  -3.04282535  -2.96528752  -0.07369432]
 [  1.63416305   1.10382732   0.39458422   0.42253152]
 [-10.17475779  -8.24225867   6.49750501  -5.60912518]
 [  4.65734644   7.66543551  -3.62841345  10.33129328]]


In [29]:
m1 = np.diag([2,4,6,8])

c1 = (m1.T + m1)/2 
c2 = m1.T@m1 

c1 - np.sqrt(c2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
m1 = randn(2,4)
m2.flatten(order = 'F') 

norm = np.linalg.norm(m1@m2)

fro = np.linalg.norm(m1, ord = 'fro') * np.linalg.norm(m2)

norm - fro

9.40398535682411